# Clarinet.toml - Project configuration
[project]
name = "hello-stacks"
description = "A simple Clarity project"
authors = ["Your Name <your.email@example.com>"]
telemetry = true
cache_dir = "./.clarinet"
requirements = []

[contracts.hello-world]
path = "contracts/hello-world.clar"
clarity_version = 2
epoch = 2.4

[repl]
costs_version = 2
parser_version = 2